### ISSUE TITLE
[Feature Request for v6] Allow imperative hiding

### ISSUE THREAD

**Issue by itswillta** [icflorescu/mantine-contextmenu-v6#6]
#### Context

With v7, the library currently allows imperative hiding: https://icflorescu.github.io/mantine-contextmenu/examples/imperative-hiding/.

However, with v6, there's no such capability. Projects like mine can't afford to upgrade from Mantine v6 to v7 as there are so many breaking changes (esp. the removal of emotion and CSS-in-JS).

#### Suggested changes

Adding imperative hiding for v6 should be straightforward as we just need to expose such a function, and then it can be published as `6.1.0` or something. @icflorescu What do you think? Thanks!

**Comment by icflorescu** [comment]
This would be kind of a breaking change, so it would definitely need to be published as `6.1.0`...
Do you feel like coming up with a PR to backport the feature from V7?

I could do it at some point in the future, but I'm not sure when I'll be able to find the time.
I'm still struggling with the finishing touches of upgrading [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) to V7 as well...

And yes, after upgrading these two projects, I feel your pain, but i'm afraid at some point you'll have to upgrade, because even the guy behind Mantine itself will not maintain the old version indefinitely.

**Comment by itswillta** [comment]
Thanks for the quick reply. Yeah I think I'll come up with a PR soon and tag you there when it's done.

I agree that we'll have to upgrade to v7 at some point, but it'll be for a later future. We've actually just migrated from v5 to v6.

**Comment by itswillta** [comment]
@icflorescu Hi, I have the code ready now, and I'm trying to create a PR. However, it seems that I don't have permission to push a new branch (or `next`) to this repo. Would you mind helping me with that?

**Comment by icflorescu** [comment]
When contributing to projects from other people, the best practice is to fork first, make changes in a local branch, then push that branch to your fork and create a pull request.

See this comment here: https://github.com/icflorescu/mantine-datatable/issues/420#issuecomment-1730101361

Also, please checkout the [contributing guide](https://github.com/icflorescu/mantine-contextmenu-v6/blob/main/CONTRIBUTING.md) in this repo - make sure to target your PR to the `next` branch.

I'm kind of reluctant about this, as it would come as a breaking change in a minor version, and we'll also have to update the documentation about the changes, as all examples are using this syntax:

```ts
const showContextMenu = useContextMenu();
```

I assume you want to change the syntax to:

```ts
const { showContextMenu, hideContextMenu } = useContextMenu();
```
...like we have in V7.

I fear this would be kind of frustrating to the users of `6.x`.
If they're not upgrading to `6.1`, they'll see a documentation that doesn't reflect their usage.
I can't think of a way to implement this in a non-breaking manner, can you?

I'm curious to hear your feedback.

**Comment by itswillta** [comment]
Oh, right. It has been a long time since the last time I ever contributed to an open-source project, and I completely forgot about the fork thing.

Yeah, I went with what's currently in v7, which will be a breaking change.

I think there's ways to implement it in a non-breaking manner. For example, we can define `showContextMenu`, `hideContextMenu`, and `isContextMenuVisible` as properties of the `showContextMenu` function itself. That way we can use it like:

```ts
const showContextMenu = useContextMenu();

// or

const { showContextMenu, hideContextMenu, isContextMenuVisible } = useContextMenu();
```

This way, the old usage remains the same. This can seem a little bit "unconventional", but it works as JavaScript allows it (JavaScript Functions are also Objects). What do you think? @icflorescu

**Comment by icflorescu** [comment]
I think this would be awesome!
And it looks like it can be done in type-safe way too (see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#properties-declarations-on-functions).

**Comment by itswillta** [comment]
> I think this would be awesome! And it looks like it can be done in type-safe way too (see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#properties-declarations-on-functions).

OK then I'll go with this approach.
